pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh 'cd coit-frontend && docker build -t mkothapally/coit-backend1:v1 -f Dockerfile-multistage .'
            }
        }
        stage('docker-push') {
            steps {
                sh 'docker push mkothapally/coit-backend1:v1'
            }
    }
}
}
