pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh 'cd coit-frontend && mvn install'
            }
        }
        stage('docker-build') {
            steps {
               sh 'cd coit-frontend && docker build mkothapally/coit-frontend:v1.4 -f Dockerfile-multistage .'
               sh 'docker images' 
            }
        }
        stage('docker-push') {
            steps {
                sh 'echo "pushing docker image"'
                sh 'docker push mkothapally/coit-frontend:v1.4'
            }
    }
}
}
